var e1 = {
  ID: 'cPRf3K90lKg',
  series_title: 'Just A Dash',
  episode_title: 'Bone Broth Brigade Oxtail Pho',
  episode_number: '1',
  description: 'PHO IS LIFE AND JUST A DASH IS BROTH LETS SIP UP SOME LOVE! THIS WEEK AND THE FIRST JUST A DASH IS EVERYTHING YOU WISHED IT WOULD BE! YOURE WELCOME',
};

var e2 = {
  ID: 'LXXUqe9JiY8',
  series_title: 'Just A Dash',
  episode_title: 'Worlds Best Halifax Doinar',
  episode_number: '2',
  description: 'THIS ONE IS FOR EVERY BLUENOSER! THE GREATEST OF ALL DONAIRS! THE GREATEST SAUCE OF ALL TIME AND SPACE WILL BE REVEALED TO THE ENTIRE WORLD AND MAYBE ITS NOT READY!',
};

var e3 = {
  ID: 'zZ9SZn7QzIM',
  series_title: 'Just A Dash',
  episode_title: 'Larb is Goooood',
  episode_number: '3',
  description: 'LARB IS THE GREATEST SALAD OF ALL TIME! PLEASE DO NOT FRY WET PIGS EARS IN YOUR HOME! I LOVE YOU AND GOOD LUCK!',
};

var e4 = {
  ID: 'QN019zyVpNI',
  series_title: 'Just A Dash',
  episode_title: 'Drop Acid & Butter Baste Steaks',
  episode_number: '4',
  description: 'ALRIGHT YOU FREAKS!!!! ITS WEDNESDAY AND ITS A NEW JUST A DASH!!!! THE PERFECT STEAK AND SALAD A MEAL OLD AS TIME LIKE THE WIND AND FALLING LEAVES TOGETHER FOREVER! I HOPE YOU LEARN HOW TO COOK STEAK AND DRESS A SALAD PERFECTLY!!!! REMEMBER TO SUBSCRIBE LIKE SHARE COMMENT AND TELL ALL YOUR BUDDIES!!!!! I LOVE YOU ALL',
};

var e5 = {
  ID: 'gODCeNysnc0',
  series_title: 'Just A Dash',
  episode_title: 'Fever Dream Duck Confit Crepes',
  episode_number: '5',
  description: 'THIS EPISODE OF JUST A DASH BRINGS ME BACK TO WORKING AT A FRENCH RESTAURANT AND MY LOVE FOR DUCK CONFIT AND MY LOVE FOR CHINESE CREPES AND LATE NIGHT RUNNING THROUGH CHINATOWN WITH CHEF RANG I LOVE COWBOY CONFIT A-LOT AND ANYONE CAN MAKE IT AND I LOVE THAT THIS DISH IS SO EASY TO MAKE AND THAT YOU GET TO WATCH ME FAIL AND COME BACK TO LIFE AND RISE LIKE THE CULINARY PHOENIX I AM AND IM ALWAYS FIGHTING FOR YOU TO LEARN AND CREATE GASTRONOMIC TREATS TO SHARE WITH THE LOVES OF YOUR LIFE',
};

var e6 = {
  ID: 'mIA9AlrJZm4',
  series_title: 'Just A Dash',
  episode_title: 'Worlds Greatest Chicken Soup',
  episode_number: '6',
  description: 'TODAY IS EVERYONES FAVOURITING WEDNESDAY ITS THE EVERY OTHER WEDNESDAY WHERE JUST A DASH COMES  OUT!!!! WE ARE MAKING POZOLE VERDE DE POLLO AND ITS MAYBE MY BEST VIDEO IVE EVER MADE BUT I SAY THAT ABOUT EVERY VIDEO BUT THIS ONE IS SPECIAL AND WILL WARM YOU TO THE BONE! ALL OF THE PATIENCE YOU FREAKY DEAKY FREAKS ARE SHOWING BY HOLDING ON IS BEAUTY AND POWER AND I LOVE ALL YALL!!!!! LETS FUCKING GO',
};

var e7 = {
  ID: 'aaa',
  series_title: 'Just A Dash',
  episode_title: 'No longer available',
  episode_number: '7',
  description: 'This is episode seven',
};

var e8 = {
  ID: 'Rlml-vE54KQ',
  series_title: 'Just A Dash',
  episode_title: 'Fearless Flavors Boiled Dinner',
  episode_number: '8',
  description: 'ITS THE FUCKING WEDNESDAY WEVE ALL BEEN WAITING FOR!!!! SCUM? CHECK! COMPLETE MELTDOWN? CHECK!  DO I PULL IT THE FUCK BACK TO ORBIT??? FUCKING YES MY DOGGY DOGS! WE ARE MAKING A BOILED DINNER TO END ALL BOILED DINNERS!!!! FROM THE BOTTOM OF MY BOILED SOUL THIS EPISODE IS BEAUTOFUL AND FULL EMOTIONS AND SHOULD HAVE WON 67 GOLDEN GLOBES! ONCE AGAIN BROUGHT TO YOU BY THE GOOD HOMIES AT APPLESTONE',
};

var e9 = {
  ID: 'YuElgJfIeUg',
  series_title: 'Just A Dash',
  episode_title: 'Scret Ingredient Shepherds Pie',
  episode_number: '9',
  description: 'I LOVE EVERY OTHER WEDNESDAYS SO MUCH YOU FREAKY DEAKY FREAKS YOU FREAKS!!!! JUST A DASH THIS WEEK IS LITERALLY MY PERSONAL FAVOURITE SO FAR AND I WATCHED IT LAST NIGHT AND I JUST THINK IM MAKING CONTENT IN THE FOOD WORLD THAT IS PERFECT AND ON THIS EPISODE YOULL SEE HOW GREAT I AM AT MAKING A SHEPARDS PIE !!! THE GREATEST OF ALL PIES CAUSE IT DOESNT EVEN HAVE A DOUGH THE DOUGH IS MASHED POTATOES AND THATS THE BEST FOOD IN THE WORLD SO HERE YOU GO ANOTHER HIT FROM THE JUST A DASH CREW PAVING THE WAY THROUGH UNCHARTERED WATERS OF THE CULINARY IDIOT OF ME! ENJOY',
};

var e10 = {
  ID: 'lKQrXsaORFA',
  series_title: 'Just A Dash',
  episode_title: 'Lamb Neck Taco Induced Visions',
  episode_number: '10',
  description: 'WHO DOESN’T LOVE TO COOK LAMB NECK AND MAKE FLOUR TORTILLAS!???!? ITS THE EVERY OTHER WEDNESDAY AND THIS EPISODE OF JUST A DASH IS SO INSIGHTFUL INTO THE WORLD OF NECKS! THESE TACOS ARE SO FUCKING FIRE AND I KNOW MY TORTILLAS LOOK LIKE SHIT CAUSE IM JUST SOME DUMMY WHO MADE THESE FOR THE FIRST TIME TOO OK?!? HAHAHAH I LOVE ALL YALL SO MUCH!!!!! JUST A DASH FOREVER!!!!!!! ENJOY YOUR LIFE AND COOK FOR PEOPLE YOU LOVE!!!!',
};

var e11 = {
  ID: '4jbSsAjkryg',
  series_title: 'Just A Dash',
  episode_title: 'Worst Best Chef Makes Chicken Fried Steaks',
  episode_number: '11',
  description: 'IN THIS PENULTIMATE EPISODE YOU WILL RECEIVE AN AWAKENING INTO THE WORLD AND MIND OF A MADMAN THROUGH THE EXPERIENCE OF THE GREATEST FOOD STYLIST EVER MICHELLE RABIN  MY SOUL SISTER MY BETTER CULINARY HALF WE ARE THE BEST WORST CULINARY TEAM OF ALL TIME AND WE WERE BIRTHED FROM THE REAL DEPTHS OF THE INTERNET TO BRING YOU A COOKING SHOW THAT BRINGS YOU TRUTHS AND LOVE AND REAL DEAL COOKING! SHE WILL BE HEARD AND ITS WHAT WE ALL EXPECTED MICHELLE LOVES ME UNDYINGLY AND I LOVE HER I AM NOTHING WITH HER AND I AM NOTHING WITHOUT HER!  THIS WEEK WE MAKE CHICKEN FRIED STEAKS LIKE THE PROS YOU KNOW WE ARE! JUST A DASH FOREVER AND JUST A DASH LOVES YOU! THANK YOU APPLESTONE MEATS FOR BELIEVING IN US!!!',
};

var e12 = {
  ID: 'jEQYWDw-1B8',
  series_title: 'Just A Dash',
  episode_title: 'A Mattys Pattys Tale',
  episode_number: '12',
  description: 'TODAY IS THE DAY MY BEAUTIFUL FREAKS ITS THE SEASON FINALE OF JUST A DASH!!!!! WE DID IT!!! WE MADE A SHOW AND YOU GUYS MY FANS FOLLOWERS LIKERS WATCHERS SHARERS SUBBYS THUMBS UPS LIKED IT LOVED IT AND MAYBE EVEN SOME HATED IT AND THATS OK! I REALLY WANT TO LET YOU KNOW HOW MUCH THIS MEANS TO ME! I MADE THIS SHOW NOT KNOWING WHAT WOULD HAPPEN AND I MADE THIS SHOW WITH MY FRIENDS AND WE DID THE BEST WE COULD AND NOW WE GET TO MAKE A NEW SEASON AND MAKE IT BIGGER AND BETTER THAN THE FIRST AND I PROMISE ITLL BE EVEN BETTER BUT THIS SHOW IS THE BEST COOKING SHOW EVER MADE AND THATS BECAUSE WE MADE IT FOR YOU BY FRIENDSHIP AND LOVE! THANK YOU TORT! THANK YOU MICHELLE! THANK YOU CAMERA BEN! THANK YOU FUCKIN SOUNDGUY! AND A HUGE THANK YOU TO JOSH AND EVERYONE APPLESTONE MEAT YOU WILL ALWAYS HAVE A PLACE IN MY HEART FOR BELIEVING AND BEING MY FIRST EVER SPONSOR THANK YOU! SEASON TWO OF JUST A DASH WILL AIR IN MAY! ',
};

var JustADash = {
  title: 'Just A Dash',
  episode: [e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12],
  description:
    'Just A Dash is not your normal tv show. Follow Matty Matheson on his cooking adventure of failure, success, and stories about life',
  image: require('../ThumbNails/JustADash.png'),
  thumbnail: require('../ThumbNails/JustADashthumb.jpg'),
  id: 1007,
};

export var JustADash;
